---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.finenomore.name }}
  namespace: {{ default .Release.Namespace .Values.namespace | quote }}
spec:
  replicas: 1
  selector:
    {{- with .Values.finenomore.labels }}
    matchLabels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  template:
    metadata:
      {{- with .Values.finenomore.labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.finenomore.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.finenomore.imagePullSecrets }}
      {{- end }}
      containers:
        - name: {{ .Values.finenomore.name }}
          image: {{ .Values.finenomore.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.finenomore.ports.internal }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.finenomore.name }}
  namespace: {{ default .Release.Namespace .Values.namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.finenomore.ports.external }}
      targetPort: {{ .Values.finenomore.ports.internal }}
  {{- with .Values.finenomore.labels }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.finenomore.name }}
  namespace: {{ default .Release.Namespace .Values.namespace | quote }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- if .Values.finenomore.ingress.prefix }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- end }}
spec:
  rules:
    - http:
        paths:
        {{- if .Values.finenomore.ingress.prefix }}
        - path: {{ .Values.finenomore.ingress.prefix }}(/|$)(.*)
        {{- else }}
        - path: "/"
        {{- end }}
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.finenomore.name }}
              port:
                number: {{ .Values.finenomore.ports.external }}
      {{- if .Values.finenomore.ingress.host }}
      host: {{ .Values.finenomore.ingress.host }}
      {{- end }}
